apiVersion: v1
kind: Reflector
spec:
  camos:
    default: # camo name for future reference
      # security currently can be
      # 'reality' - steal someone's tls
      # 'wtls' - web/www tls (to distinguish from xray 'tls'), 
      #          setup a caddy web server as a decoy
      security: reality

      # domain name to steal tls from (reality)
      fqdn: google.com

  inbounds:
    - name: vless-in
      type: vless
      camo: default
      listen: 0.0.0.0
      listen_port: 8443
      transport: tcp

      # reality privkey
      private_key: KMDYAHPo2W2ycEGSEhRV7KWDgKcL6vjvgw57iPdsF0g
      users:
        - name: bob
          uuid: bb3bb3bb-bbbb-bbbb-bbbb-bb3bbbbbb3bb
          flow: 'xtls-rprx-vision'
          short_id: b0b01d

  outbounds:
    - name: direct
      type: direct

  routes:
    - user: bob
      outbound: direct
